sonar.organization=GitOpsGarage
sonar.projectKey=calendario-copa-2026

sonar.sources=.
sonar.exclusions=node_modules/**,.devcontainer/**,.claude/**,.opencode/**,.github/**

sonar.javascript.lcov.reportPaths=
